CREATE DATABASE EVENTOS_BBDD;
USE EVENTOS_BBDD;

CREATE TABLE TIPOS
(ID_TIPO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(45) NOT NULL,
DESCRIPCION VARCHAR(200)
);

CREATE TABLE USUARIOS
(
USERNAME VARCHAR(45) NOT NULL PRIMARY KEY,
PASSWORD VARCHAR(45) NOT NULL,
EMAIL VARCHAR(100) NOT NULL UNIQUE,
NOMBRE VARCHAR(30),
APELLIDOS VARCHAR(45),
DIRECCION VARCHAR(100),
ENABLED INT NOT NULL DEFAULT 1,
FECHA_REGISTRO DATE
);

CREATE TABLE PERFILES
(ID_PERFIL INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(45) NOT NULL
);

CREATE TABLE USUARIO_PERFILES
(USERNAME VARCHAR(45),
ID_PERFIL INT NOT NULL,
PRIMARY KEY(USERNAME, ID_PERFIL),
FOREIGN KEY(USERNAME) REFERENCES USUARIOS(USERNAME),
FOREIGN KEY(ID_PERFIL) REFERENCES PERFILES(ID_PERFIL)
);

CREATE TABLE EVENTOS
(ID_EVENTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(50) NOT NULL,
DESCRIPCION VARCHAR(200),
FECHA_INICIO DATE,
FECHA_FIN DATE,
DURACION INT,
DIRECCION VARCHAR(100),
ESTADO ENUM('ACEPTADO','TERMINADO','CANCELADO'),
DESTACADO ENUM('S','N'),
AFORO_MAXIMO INT,
MINIMO_ASISTENCIA INT,
PRECIO DEC(9,2),
ID_TIPO INT NOT NULL,
FOREIGN KEY(ID_TIPO) REFERENCES TIPOS(ID_TIPO)

);

CREATE TABLE RESERVAS
(ID_RESERVA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
ID_EVENTO INT NOT NULL,
USERNAME VARCHAR(45)  NOT NULL,
PRECIO_VENTA DEC(9,2),
OBSERVACIONES VARCHAR(200),
CANTIDAD INT,
FOREIGN KEY(USERNAME) REFERENCES USUARIOS(USERNAME),
FOREIGN KEY(ID_EVENTO) REFERENCES EVENTOS(ID_EVENTO),
check(cantidad between 1 and 10),
UNIQUE(ID_EVENTO,USERNAME)
);

-- Insertar datos en la tabla TIPOS
INSERT INTO TIPOS (NOMBRE, DESCRIPCION) VALUES
('Conferencia', 'Evento para compartir conocimientos sobre un tema específico'),
('Taller', 'Evento práctico para aprender habilidades'),
('Seminario', 'Evento académico o profesional');

-- Insertar datos en la tabla USUARIOS
INSERT INTO USUARIOS (USERNAME, PASSWORD, EMAIL, NOMBRE, APELLIDOS, DIRECCION, ENABLED, FECHA_REGISTRO) VALUES
('deivi', '{noop}deivi', 'deivi@example.com', 'David', 'Garcia', 'Calle Sol, 123', 1, CURDATE()),
('tomas', '{noop}tomas', 'tomas@example.com', 'Tomas', 'Perez', 'Calle Luna, 45', 1, CURDATE()),
('ana', '{noop}ana', 'ana@example.com', 'Ana', 'Lopez', 'Avenida Mar, 78', 1, CURDATE());


-- Insertar datos en la tabla PERFILES
INSERT INTO PERFILES (NOMBRE) VALUES
('ROLE_ADMON'),
('ROLE_CLIENTE');

-- Asignar perfiles a usuarios en la tabla USUARIO_PERFILES
INSERT INTO USUARIO_PERFILES (USERNAME, ID_PERFIL) VALUES
('deivi', 1), -- David es Admin
('tomas', 2), -- Tomas es Usuario
('ana', 2);   -- Ana es Usuario

-- Insertar datos en la tabla EVENTOS
INSERT INTO EVENTOS (NOMBRE, DESCRIPCION, FECHA_INICIO, FECHA_FIN, DURACION, DIRECCION, ESTADO, DESTACADO, AFORO_MAXIMO, MINIMO_ASISTENCIA, PRECIO, ID_TIPO) VALUES
('Taller de Java', 'Aprende los fundamentos de Java', '2024-01-15','2024-02-15', 3, 'Calle Programación, 1', 'ACEPTADO', 'S', 50, 10, 100.00, 2),
('Seminario de Negocios', 'Tendencias en el mundo empresarial', '2024-02-20','2024-03-15', 1, 'Calle Negocios, 10', 'TERMINADO', 'N', 100, 20, 200.00, 3),
('Conferencia de Tecnología', 'Explora las nuevas tecnologías del mercado', '2024-03-10','2024-04-15', 2, 'Calle Innovación, 15', 'CANCELADO', 'N', 200, 30, 150.00, 1);

-- Insertar datos en la tabla RESERVAS
INSERT INTO RESERVAS (ID_EVENTO, USERNAME, PRECIO_VENTA, OBSERVACIONES, CANTIDAD) VALUES
(1, 'deivi', 90.00, 'Asiento preferencial', 2),
(2, 'tomas', 180.00, 'Entrada regular', 1),
(3, 'ana', 135.00, 'Promoción de estudiante', 1),
(1, 'tomas', 90.00, 'Asiento regular', 1),
(2, 'ana', 180.00, 'Entrada VIP', 2),
(3, 'deivi', 135.00, 'Promoción de estudiante', 1);

